### ISSUE TITLE
Misiing files in Pypi SDIST

### ISSUE THREAD

**Issue by onkelbeh** [StefanIacobLivisi/aiolivisi#2]
```
>>> Emerging (1 of 1) dev-python/aiolivisi-0.0.14::HomeAssistantRepository
>>> Failed to emerge dev-python/aiolivisi-0.0.14, Log file:
>>>  '/var/tmp/portage/dev-python/aiolivisi-0.0.14/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.54, 0.28, 0.20
 * Package:    dev-python/aiolivisi-0.0.14:0
 * Repository: HomeAssistantRepository
 * Maintainer: b@edevau.net
 * Upstream:   stefan.iacob.extern@livisi.de
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_10 test userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking aiolivisi-0.0.14.tar.gz to /var/tmp/portage/dev-python/aiolivisi-0.0.14/work
>>> Source unpacked in /var/tmp/portage/dev-python/aiolivisi-0.0.14/work
>>> Preparing source in /var/tmp/portage/dev-python/aiolivisi-0.0.14/work/aiolivisi-0.0.14 ...
 * Build system packages:
 *   dev-python/gpep517            : 9
 *   dev-python/installer          : 0.5.1-r1
 *   dev-python/setuptools         : 65.5.1
 *   dev-python/setuptools_scm     : 7.0.5
 *   dev-python/wheel              : 0.38.4
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/aiolivisi-0.0.14/work/aiolivisi-0.0.14 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/aiolivisi-0.0.14/work/aiolivisi-0.0.14 ...
 * python3_10: running distutils-r1_run_phase distutils-r1_python_compile
 *   Building the wheel for aiolivisi-0.0.14 via setuptools.build_meta:__legacy__
gpep517 build-wheel --backend setuptools.build_meta:__legacy__ --output-fd 3 --wheel-dir /var/tmp/portage/dev-python/aiolivisi-0.0.14/work/aiolivisi-0.0.14-python3_10/wheel
2022-12-08 09:00:02,659 gpep517 INFO Building wheel via backend setuptools.build_meta:__legacy__
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/gpep517", line 4, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 322, in main
    return func(args)
  File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 122, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
  File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 105, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 412, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
    self.run_setup()
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 483, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
    exec(code, locals())
  File "<string>", line 7, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
 * ERROR: dev-python/aiolivisi-0.0.14::HomeAssistantRepository failed (compile phase):
 *   Wheel build failed
```

**Comment by onkelbeh** [comment]
For 0.0.14 I now have choosen 975ffc8e3c824b75bfa21de1aab89b6467a078b0, hope it is correct.

**Comment by onkelbeh** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt' still missing for 0.15

**Comment by onkelbeh** [comment]
sorry "please see https://github.com/StefanIacobLivisi/aiolivisi/pull/3", was mentioned in the wrong ticket.
